#!/bin/bash

mkdir /boot/extlinux
cp -r /lib/syslinux/modules/bios /boot/extlinux

cat <<EOF > /boot/extlinux/extlinux.conf
DEFAULT Debian

LABEL Debian
	KERNEL /boot/$(ls /boot | grep vmlinuz)
	APPEND root=/dev/sda1 rw
	INITRD /boot/$(ls /boot | grep initrd)
EOF

cat /lib/syslinux/mbr/mbr.bin > /dev/sda
extlinux --install /boot/extlinux

sudo apt install extlinux syslinux
sudo apt-get purge libfreetype6 libfuse2 libpng16-16 grub

cat <<EOF > /etc/apt/apt.conf.d/01norecommends
APT::Install-Recommends "0";
APT::Install-Suggests "0";
APT::AutoRemove::RecommendsImportant "0";
APT::AutoRemove::SuggestsImportant "0";
EOF

sudo apt autoremove
sudo apt install chromium chromium-l10n
sudo apt install git ca-certificates curl
git clone https://gitea.com/sorathpanzer/dotgit.git
sudo apt install build-essential libx11-dev libxft-dev libxinerama-dev libimlib2-dev libexif-dev
sudo apt install udiskie x11-xserver-utils xinput pulseaudio pulseaudio-utils pulsemixer hsetroot ntfs-3g fuse picom numlockx xdotool man
sudo apt install zsh zsh-syntax-highlighting zsh-autosuggestions fzf exa bat doas trash-cli youtube-dl mpv xclip neovim
curl -L https://github.com/gokcehan/lf/releases/download/r24/lf-linux-amd64.tar.gz | tar xzC ~/.local/bin
sudo echo "kernel.perf_cpu_time_max_percent = 0" >> /etc/sysctl.conf
git clone https://github.com/Earnestly/sx
cd sx
sudo make PREFIX=/usr install
cd
