#!/bin/bash

USERNAME=""
PASSWORD=""

apt install -y extlinux syslinux
mkdir /boot/extlinux
cp -r /lib/syslinux/modules/bios /boot/extlinux

cat <<EOF > /boot/extlinux/extlinux.conf
DEFAULT Debian

LABEL Debian
	KERNEL /boot/$(ls /boot | grep vmlinuz)
	APPEND root=/dev/sda1 rw
	INITRD /boot/$(ls /boot | grep initrd)
EOF

cat /lib/syslinux/mbr/mbr.bin > /dev/sda
extlinux --install /boot/extlinux

apt-get purge -y libfreetype6 libfuse2 libpng16-16 grub

cat <<EOF > /etc/apt/apt.conf.d/01norecommends
APT::Install-Recommends "0";
APT::Install-Suggests "0";
APT::AutoRemove::RecommendsImportant "0";
APT::AutoRemove::SuggestsImportant "0";
EOF

echo "kernel.perf_cpu_time_max_percent = 0" >> /etc/sysctl.conf

apt autoremove -y
apt install -y chromium chromium-l10n stow
apt install -y git ca-certificates curl

printf "$PASSWORD\n$PASSWORD" | sudo -Hu $USERNAME git clone https://gitea.com/sorathpanzer/dotgit.git /home/$USERNAME/.config/dotgit
printf "$PASSWORD\n$PASSWORD" | sudo -Hu $USERNAME mkdir -p /home/$USERNAME/.cache/zsh
printf "$PASSWORD\n$PASSWORD" | sudo -Hu $USERNAME touch /home/$USERNAME/.cache/zsh/history
rm $HOME/.profile
printf "$PASSWORD\n$PASSWORD" | sudo -Hu $USERNAME sh -c "cd /home/$USERNAME/.config/dotgit; stow -vt ~ dotfiles"
printf "$PASSWORD\n$PASSWORD" | sudo -Hu $USERNAME sh -c "curl -L https://github.com/gokcehan/lf/releases/download/r24/lf-linux-amd64.tar.gz | tar xzC ~/.local/bin"

apt install -y build-essential libx11-dev libxft-dev libxinerama-dev libimlib2-dev libexif-dev xorg xauth
apt install -y udiskie x11-xserver-utils xinput pulseaudio pulseaudio-utils pulsemixer hsetroot ntfs-3g fuse picom numlockx xdotool man
apt install -y zsh zsh-syntax-highlighting zsh-autosuggestions fzf exa bat doas trash-cli youtube-dl mpv xclip neovim

git clone https://github.com/Earnestly/sx
cd sx
make PREFIX=/usr install
cd
rm -r sx

apt install -y gir1.2-gst-plugins-base-1.0 gir1.2-gst-plugins-bad-1.0 xdg-user-dirs wireless-tools iwd ripgrep mediainfo bat pass xdotool highlight
apt install -y libreoffice libreoffice-l10n-pt imagemagick transmission-cli fonts-dejavu ntp  bc pulseaudio hsetroot alsa-utils firewalld apparmor
apt install -y xclip numlockx scrot rsync zathura doas udiskie trash-cli dunst youtube-dl physlock picom jq fzf mpv wmctrl light patch
apt install -y unzip usbutils ffmpegthumbnailer pulsemixer rkhunter clamav 
 
sudo systemctl enable ntp

echo "permit persist $USERNAME as root
permit nopass $USERNAME cmd apt
permit nopass $USERNAME cmd journalctl
permit nopass $USERNAME cmd poweroff
permit nopass $USERNAME cmd reboot
permit nopass $USERNAME cmd udiskctl
permit nopass $USERNAME cmd mount
permit nopass $USERNAME cmd light" > /mnt/etc/doas.conf

echo "vm.swappiness=10" > /mnt/etc/sysctl.d/99-sysctl.conf
echo 1 | sudo tee /sys/module/snd_hda_intel/parameters/power_save

#ueberzug lazygit alacritty
